name: INDUSTRYOUS Photography
favicon: null
layout_spectrum: 0.74735
typography_spectrum: 0.36189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242d36'
    - '#43515c'
    - '#9fa8a3'
    - '#797b70'
    - '#b9bbae'
  brandStrength: 0.625
  lightness: 0.7248898958787322
  saturation: 0.5
  rhythmicContrast: 0.6479308272246271
purpose: []
