name: INDUSTRYOUS Photography
favicon: null
layout_spectrum: 0.4535469743423164
typography_spectrum: 0.5485233897343278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2863105854485184
  lightness: 0.7248898958787322
  saturation: 0.8857644603122026
  rhythmicContrast: 0.6479308272246271
purpose: []
